### ISSUE TITLE
Runtime assert detect -inf value

### ISSUE THREAD

**Issue by james34602** [praffensperger/wavechild670#1]
Compile using MSVC 2015/2017
Print out: Failure at tubemodel.cpp : 48
Trace at BidirectionalUnitDelayInterface* cathodeCapacitorConn in wdfcircuits.h.
wdfcircuits.h line 215 occur: Real b = -inf
Possibly due to getB first argument tubeSeriesConn2_3b3 is uninitialised.
Further trace: Real cathodeCapSeriesConn_3b3 is also uninitialised due to cathodeCapacitorConn->getB() is uninitialised.

**Comment by james34602** [comment]
Working wavechild670 ported to C: [Source code](https://github.com/james34602/JamesDSPManager/tree/master/Audio_Engine/eclipse_libjamesdsp_many_bands_Lollipop_Marshmallow_Nougat_PartialMultithread/jni/valve)
And some comparison chart to show nonlinearity using Matlab, [Graph](https://github.com/james34602/JamesDSPManager/tree/master/Misc/Valve)
There no numerical different using Debug build compared to fixed C++ version.

**Comment by creer** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
DarthTicius, @khanduri, @appleboy, @chrispk, @llvvrui, @rsuhendro, @frankk00, @madsurgeon, @ngEdmundas, @henryfour, @tlightsky, @shardwick, @gilescope, @meta-machine, @crkacer, @Filmaluco, @michaelmcclimon, @johnhenry, @spankratov, @mansfiem, @bcphung, @nomaanhussain, @bmorelax, @theoctagon1242, @KeshavJha, @cadorn, @sirlupinwatson, @LinArcX, @arden, @theopomies, @heliodor, @khalid79, @willzhuang, @tenshun, @Hamza2404, @RobbieClarken, @ropeks, @gokitchen, @jtsiros, @mac-code, @Solertis, @SylTi, @ibrmora, @oliverjumpertz, @taisukemino, @zapnap, @YoonjaeYoo, @blokboy, @granda, @ijingo
